### PR TITLE
Add testing and Fedora updating through packit

### PR DESCRIPTION
**Pull request by martinpitt**
See https://packit.dev

### CODE REVIEW

**Comment by martinpitt** [comment]
@hadess FYI -- it's high time for a new upstream release and updating Fedoras. I'd like to do this through packit, just like umockdev. I am not currently a maintainer for the Fedora package, so won't be able to approve/land the PRs myself. But it hopefully makes things simpler for you.

**Comment by hadess** [comment]
You should contact Neil Gompa about it. I don't maintain python-dbusmock despite having done most work on it over the years.

**Comment by martinpitt** [comment]
@hadess: Thanks, I pinged @Conan-Kudo in https://src.fedoraproject.org/rpms/python-dbusmock/pull-request/10

**Comment by Conan-Kudo** [comment]
@martinpitt I've given you access to the package. Unfortunately, dbusmock has slipped through the cracks for me, so more maintainers are appreciated! :)

**Pull request merged**
