### PR TITLE
Add mock server for low-memory-monitor

### PR DESCRIPTION
**Pull request by hadess**
API version 2.0

https://gitlab.freedesktop.org/hadess/low-memory-monitor/

### CODE REVIEW

**Comment by hadess** [comment]
I've figured out how to run the tests, so I fix the template and the test :)

**Comment by martinpitt** [comment]
Huh, travis, where are  you.. It seems this never ran in Travis, perhaps some GitHub webhook hiccup?

Anyway, some questions: This is a rather simple interface, and the test basically just tests dbusmock itself -- it doesn't call any external CLI or other "real" tool to make sure that the mock conforms to what a real client program expects. What e. g. tests/test_upower.py does against the `upower` cli, or tests/test_logind.py against `loginctl`. But I suppose that's ok, this doesn't look like the kind of service that has a standalone CLI.

But I wonder how useful this is actually going to be with shipping in dbusmock? You can send a signal with [a single method call](https://github.com/martinpitt/python-dbusmock/blob/master/tests/test_api.py#L396) to dbusmock in any test suite that uses the monitor, so it's not really simpler (actually, it's rather *harder*) to use this new template.

So, if you want to go ahead with this and wait until it made its way into all stable distros etc., I won't veto it. But I wonder if that's really an useful approach for what you plan to do? I. e. will you have that many new project tests that share this template, and avoiding the repetition of a single `.EmitSignal()` call is worth that?

Thanks!

**Comment by hadess** [comment]
It allows me to focus on the client side of the problem when writing tests, as in those:
https://gitlab.gnome.org/GNOME/glib/merge_requests/1005

**Comment by hadess** [comment]
Making use of GMemoryMonitor in the test isn't out of the question when it's finally landed in GLib...

**Comment by martinpitt** [comment]
OK, thanks. I fixed the travis problem, can you please force-push again to trigger them? I'll land afterwards.

**Comment by martinpitt** [comment]
Thanks! Some code style errors:

```
======================================================================

FAIL: test_codestyle (test_code.StaticCodeTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/tmp/source/tests/test_code.py", line 41, in test_codestyle

    self.assertEqual(pep8.returncode, 0, out)

AssertionError: 1 != 0 : ./tests/test_low_memory_monitor.py:27:1: E302 expected 2 blank lines, found 1

======================================================================

FAIL: test_pyflakes (test_code.StaticCodeTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/tmp/source/tests/test_code.py", line 34, in test_pyflakes

    self.assertEqual(flakes.returncode, 0, out)

AssertionError: 1 != 0 : ./tests/test_low_memory_monitor.py:23: 'gi.repository.GLib' imported but unused

./dbusmock/templates/low_memory_monitor.py:22: 'dbusmock.mockobject' imported but unused

./dbusmock/templates/low_memory_monitor.py:23: 'dbusmock' imported but unused
```

**Comment by martinpitt** [comment]
One more to go:

   ./dbusmock/templates/low_memory_monitor.py:22: 'dbusmock.mockobject' imported but unused

**Comment by hadess** [comment]
> One more to go:
> 
> ./dbusmock/templates/low_memory_monitor.py:22: 'dbusmock.mockobject' imported but unused

Sorry, I really thought I got them all otherwise I would have installed pyflakes.

**Pull request merged**
