### PR TITLE
templates/polkitd: Also mock 'RegisterAuthenticationAgent()'

### PR DESCRIPTION
**Pull request by jadahl**
Part of an attempt to run GNOME Shell with python-dbusmock

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thank you! Did that work for you, and is it complete enough, or are you still working on this?

**Comment by jadahl** [comment]
> Thank you! Did that work for you, and is it complete enough, or are you still working on this?

It did (at least I didn't see any complaint about anything more in the logs), but I think @3v1n0 had something he thought could be added here too, so maybe wait a bit.

**Comment by 3v1n0** [comment]
Yeah so since we were here, we've some changes in fprintd that would be nice to upstream, so here they are: https://github.com/jadahl/python-dbusmock/pull/1/

**Comment by jadahl** [comment]
@martinpitt this now has @3v1n0 changes too, so should be ready.

**Review by martinpitt — APPROVED** [review]
Very cool, thanks!

**Pull request merged**
